// import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import "bootstrap/dist/css/bootstrap.min.css";

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <nav className="navbar navbar-expand-lg navbar-light bg-light p-2 mb-3 ps-5">
                    <ul className="navbar-nav mr-auto ps-5">
                        <li className="nav-item me-3">
                            <Link className="nav-link text-decoration-none fw-bold" href="/">
                                Home
                            </Link>
                        </li>
                        <li className="nav-item me-3 ">
                            <Link className="nav-link text-decoration-none fw-semibold" href="/server">
                                Server
                            </Link>
                        </li>
                        <li className="nav-item me-3">
                            <Link className="nav-link text-decoration-none fw-semibold" href="/client">
                                Client
                            </Link>
                        </li>
                        <li className="nav-item me-3">
                            <Link className="nav-link text-decoration-none fw-semibold" href="/staticprops">
                                Static Props
                            </Link>
                        </li>
                    </ul>
                </nav>

                {children}
            </body>
        </html>
    );
}
